### ISSUE TITLE
Deepin V20 运行报错

### ISSUE THREAD

**Issue by JackKing-defier** [Hunlongyu/ZY-Player#233]
snap run zy
具体报错信息如下：
A JavaScript error occurred in the main process
Uncaught Exception:                                                                                           
Error: listen EADDRINUSE: address already in use :::44444                                                     
    at Server.setupListenHandle [as _listen2] (net.js:1306:16)                                                
    at listenInCluster (net.js:1354:12)                                                                       
    at Server.listen (net.js:1442:7)                                                                          
    at Function.listen (/snap/zy/x1/resources/app.asar/node_modules/express/lib/application.js:618:24)        
    at Module.<anonymous> (/snap/zy/x1/resources/app.asar/background.js:2:228902)                             
    at r (/snap/zy/x1/resources/app.asar/background.js:2:110)                                                 
    at Object.<anonymous> (/snap/zy/x1/resources/app.asar/background.js:2:111291)                             
    at r (/snap/zy/x1/resources/app.asar/background.js:2:110)                                                 
    at /snap/zy/x1/resources/app.asar/background.js:2:902                                                     
    at Object.<anonymous> (/snap/zy/x1/resources/app.asar/background.js:2:912)                                
(node:19448) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.

**Comment by Hunlongyu** [comment]
这个是端口被占用, 44444 这个端口被其他软件占用
![image](https://user-images.githubusercontent.com/15273630/94089337-81142100-fe45-11ea-9916-86814a970fc9.png)
进入任务管理器, 找到 PID 为 44444 的软件, 结束进程

**Comment by JackKing-defier** [comment]
感谢您的回复，已经找到：
```shell
master   12613 10140  0 10:33 pts/1    00:00:00 grep 44444
```
```shell
10140 pts/1    00:00:00 bash
```
但是我现在遇到了另外一个问题，软件UI界面全是白框。我已配置 locale，支持UTF-8，GBK。但依旧显示白框，请问是什么问题？
![image](https://user-images.githubusercontent.com/14344034/94094671-a4919880-fe52-11ea-9335-98073bb3448f.png)
![截图录屏_选择区域_20200924104310](https://user-images.githubusercontent.com/14344034/94094717-c428c100-fe52-11ea-9d5b-390bfb929535.png)

**Comment by Hunlongyu** [comment]
不清楚怎么解决呢~ 话说问题找到了吗?

**Comment by JackKing-defier** [comment]
嗐，后来系统也遇到了硬盘读取错误问题，猜测可能是驱动问题，感慨deepin确实总有莫名其妙的问题。为了更好地体验你开发的这个应用，我怒而重装Windows。

**Comment by buvta** [comment]
显示方块与字体及字符集有关
