### ISSUE TITLE
MAC上无法关闭和最小化

### ISSUE THREAD

**Issue by steelcanon** [Hunlongyu/ZY-Player#53]
Uncaught Exception:
TypeError: Cannot read property 'close' of null
    at IpcMainImpl.<anonymous> (/private/var/folders/80/_2j19wys7b968_l1pkjlz0900000gn/T/AppTranslocation/478D38E5-AC10-4067-9645-17C5C541DCBC/d/ZY Player.app/Contents/Resources/app.asar/background.js:2:513709)
    at IpcMainImpl.emit (events.js:223:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:4093:15)
    at WebContents.emit (events.js:223:5)

**Comment by Hunlongyu** [comment]
最新正式版: v2.x 已发布, 欢迎体验.
