### ISSUE TITLE
2.7.0 Mac dmg文件安装后无法打开

### ISSUE THREAD

**Issue by chy9002** [Hunlongyu/ZY-Player#593]
如题

以下是错误信息:

```log
Uncaught Exception:
Error: Error: ENOENT: no such file or directory, mkdir '/Users/colincai/Library/Application Support/Caches/zy-updater'
at /Applications/ZY Player.app/Contents/Resources/app.asar/background.js:2:168083
at Object.<anonymous> (/Applications/ZY Player.app/Contents/Resources/app.asar/background.js:2:168098)
at r (/Applications/ZY Player.app/Contents/Resources/app.asar/background.js:2:110)
at Object.get [as autoUpdater] (/Applications/ZY Player.app/Contents/Resources/app.asar/background.js:2:33236)
at Module.<anonymous> (/Applications/ZY Player.app/Contents/Resources/app.asar/background.js:2:549397)
at r (/Applications/ZY Player.app/Contents/Resources/app.asar/background.js:2:110)
at Object.<anonymous> (/Applications/ZY Player.app/Contents/Resources/app.asar/background.js:2:194996)
at r (/Applications/ZY Player.app/Contents/Resources/app.asar/background.js:2:110)
at /Applications/ZY Player.app/Contents/Resources/app.asar/background.js:2:902
```

**Comment by chy9002** [comment]
问题是Application Support目录下没有Caches导致的

**Comment by wei0908** [comment]
> 问题是Application Support目录下没有Caches导致的

建立了文件夹也不行呢？怎么解决呢？

**Comment by chy9002** [comment]
> > 问题是Application Support目录下没有Caches导致的
> 
> 建立了文件夹也不行呢？怎么解决呢？

建议把错误贴出来，这样才知道错误在哪
