### ISSUE TITLE
更新报错，重新安装打不开A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by 89Jockin** [Hunlongyu/ZY-Player#601]
**描述错误**
Uncaught Exception:
Error: Error: ENOENT: no such file or directory, mkdir '/Users/user/Library/Application Support/Caches/zy-updater'
    at /Volumes/ZY Player 2.7.0/ZY Player.app/Contents/Resources/app.asar/background.js:2:168083
    at Object.<anonymous> (/Volumes/ZY Player 2.7.0/ZY Player.app/Contents/Resources/app.asar/background.js:2:168098)
    at r (/Volumes/ZY Player 2.7.0/ZY Player.app/Contents/Resources/app.asar/background.js:2:110)
    at Object.get [as autoUpdater] (/Volumes/ZY Player 2.7.0/ZY Player.app/Contents/Resources/app.asar/background.js:2:33236)
    at Module.<anonymous> (/Volumes/ZY Player 2.7.0/ZY Player.app/Contents/Resources/app.asar/background.js:2:549397)
    at r (/Volumes/ZY Player 2.7.0/ZY Player.app/Contents/Resources/app.asar/background.js:2:110)
    at Object.<anonymous> (/Volumes/ZY Player 2.7.0/ZY Player.app/Contents/Resources/app.asar/background.js:2:194996)
    at r (/Volumes/ZY Player 2.7.0/ZY Player.app/Contents/Resources/app.asar/background.js:2:110)
    at /Volumes/ZY Player 2.7.0/ZY Player.app/Contents/Resources/app.asar/background.js:2:902
    at Object.<anonymous> (/Volumes/ZY Player 2.7.0/ZY Player.app/Contents/Resources/app.asar/background.js:2:913)
**重现**
重现行为的步骤

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。
![WechatIMG495](https://user-images.githubusercontent.com/17263411/103146393-6ecabb80-4783-11eb-829f-e5ced45f733d.jpeg)

**环境：**
  -操作系统及版本：Mac OS 10.12.6 (16G2136)
  -软件安装包及版本：2.7.0

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by buvta** [comment]
#593
